    <!--Pricing Tab-->
    <?php

    $idpsettings = $block->getExtensionPageUrl('idpsettings');
    $hostname = $block->getMiniOrangeUrl();
    $email = $block->getCustomerEmail();
    $version = $block->getCurrentVersion();



?>

    <div class="page" id="pricing">
    <section class="pricing py-5">
    <div class="container">
      <div class="row" >
        <!-- Free Tier -->


       <div class="columns" style="width:30%;margin-left:0%;">
         <ul class="price">
           <li class="header" style="background-color: #e85d22; text-align:center">2FA FREE  <small style="font-size:13px"> <?php print_r($version); ?> </small> (Current) </li>
           <li>&#10148;Authentication Methods (Limited Methods)</li>
           <li>&#10148; OTP Over SMS (10 SMS)</li>
             <li>&#10148; OTP Over Email (10 Email)</li>
             <li>&#10148; OTP Over SMS and Email (10 SMS & EMAIL)</li>
             <li>&#10148; Google Authenticator (10 Auto create user)</li>
             <li>&#10148; Allow specific 2fa methods to configure in inline registration</li>
             <li>&#10148; User management (reset user's 2fa method)</li>
             <li>&#10148; Backdoor URL as Backup method in case user unable to login via 2fa</li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>
             <li> </li>

          </ul>
       </div>

       <div class="columns" style="width:30%">
         <ul class="price">
             <li class="header" style="text-align:center">2FA-Backend </li>

             <li>&#10148; 15+ Authentication Methods</li>
               <li>&#10148; Allow specific 2fa methods to configure in inline registration</li>
               <li>&#10148; Email SMTP Custom Gateway</li>
               <li>&#10148; SMS Custom Gateway (Twilio/ Get Method/ Post Method)</li>
               <li>&#10148; Customize Email Templates</li>
               <li>&#10148; Customize SMS Templates</li>
               <li>&#10148; User management (reset user's 2fa method)</li>
               <li>&#10148; Backend Role base 2fa</li>
               <li>&#10148; Backdoor URL as Backup method in case user unable to login via 2fa</li>
               <li>&#10148; Reconfigure/ change 2fa method for admin</li>
               <li> </li>
               <li> </li>
               <li> </li>
               <li> </li>
               <li> </li>
               <li> </li>
             <li> </li>
             <li> </li>
               <li style="text-align:center!important"><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+TwoFA+Premium+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+TwoFA+Premium+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Upgrade</a>
             </li>

         </ul>
       </div>

       <div class="columns" style="width:30%">
         <ul class="price">
             <li class="header" style="text-align:center">2FA-Frontend/Backend  </li>

             <li>&#10148; 15+ Authentication Methods</li>
               <li>&#10148; Allow specific 2fa methods to configure in inline registration</li>
               <li>&#10148; Email SMTP Custom Gateway</li>
               <li>&#10148; SMS Custom Gateway (Twilio/ Get Method/ Post Method)</li>
               <li>&#10148; Customize Email Templates</li>
               <li>&#10148; Customize SMS Templates</li>
               <li>&#10148; User management (reset user's 2fa method)</li>
               <li>&#10148; Backend Role base 2fa</li>
               <li>&#10148; Backdoor URL as Backup method in case user unable to login via 2fa</li>
               <li>&#10148; Reconfigure/ change 2fa method for admin</li>
               <li>&#10148; Set Different 2fa method for multiple sites.</li>
               <li>&#10148; Customer group/Role Based 2FA </li>
               <li>&#10148; Enforce 2fa at registration for customers</li>
               <li>&#10148; KBA as backup method incase customer unable to login via 2fa</li>
               <li>&#10148; Customize Ui of login UI popup</li>
               
             <li style="text-align:center!important;margin-top:8px"><a href="https://mail.google.com/mail/u/0/?fs=1&amp;tf=cm&amp;source=mailto&amp;su=Query+to+purchase+Magento+TwoFA+Premium+Plan+&amp;to=magentosupport@xecurify.com&amp;body=I+want+to+enquire+about+the+purchase+of+the+Magento+TwoFA+Premium+Plan.+" target="_blank" rel="nofollow" class="button btn-round" style="font: size 14px;px;padding:7px 12px">Upgrade</a>
             </li>

         </ul>
       </div>


   </div>


    </div>

  </section>
    </div>

<div>

<p> Contact us at <a href="mailto:magentosupport@xecurify.com">magentosupport@xecurify.com</a> for more info.</p><br>


</div>


